### ISSUE TITLE
For loop Off-By-One in jsonStringifyObject

### ISSUE THREAD

**Issue by jackbilesisdm** [DavidVine/amx-util-library#2]
I was recently working with this library to get some WebSocket functionality running with other devices on the same netowrk switch.

I ran into an empty json object `{}` when trying to post a singular line of data in the object.

*EDIT*

- I have checked and the `jObj.pairs` in `json.axi` and is returning a length of 0, so it is skipping out the loop all together,

Main.axs
```
DEFINE_FUNCTION webSocketOnOpen(DEV socket) { //On WebSocket Connection
	STACK_VAR jsonObj obj
	stack_var char aString[255]
        if(socket == dvVCUnit01) {
			  
	   obj.pairs[1].name = 'first name'
	   obj.pairs[1].jtoken.type = JSON_TYPE_STRING
	   obj.pairs[1].jtoken.value = 'a value'
					
	   obj.pairs[2].name = 'last name'
	   obj.pairs[2].jtoken.type = JSON_TYPE_STRING
	   obj.pairs[2].jtoken.value = 'a value'
					
	   len = length_array(obj.pairs)
					  
	   aString = jsonStringifyObject(obj)

	   webSocketSend(socket, aString)
        }
}
```

json.axi
```
define_function char[JSON_MAX_VALUE_DATA_LENGTH] jsonStringifyObject(JsonObj jObj) {
	char objStr[JSON_MAX_VALUE_DATA_LENGTH];
	integer i;
	
	objStr = '{';
	
	for(i=1; i<=length_array(jObj.pairs); i++) {
		if(i == length_array(jObj.pairs)) {
			objStr = "objStr,'"',jObj.pairs[i].name,'":',jsonStringifyValue(jObj.pairs[i].jToken)";
		}
		else {
			objStr = "objStr,'"',jObj.pairs[i].name,'":',jsonStringifyValue(jObj.pairs[i].jToken),','";
		}
	}
	
	objStr = "objStr,'}'"
	
	return objStr;
}
```

server.js
```
output: {}
```

**Comment by DavidVine** [comment]
Hi Jack,
Thanks for posting this issue. Are you able to post a sample of the JSON data you were working with so I can try to replicate?

**Comment by jackbilesisdm** [comment]
Hey David,

Please see my edit above

**Comment by DavidVine** [comment]
Hi Jack,
I think I see the problem....
When you're building the jsonObj and adding data to its pairs array you're not setting the length of the array. By default the length of all arrays is zero (unless assigned a value on the same line of declaration). CHAR arrays have their length set automatically through string assignment operations but the length of an array is unchanged when assigning values to an arrays individual indexes.
Use the SET_LENGTH_ARRAY function to manually set the length of obj.pairs to 2 prior to calling the jsonStringifyObject function.

**Comment by jackbilesisdm** [comment]
I see,

Thanks for the quick fix David!

Closing thread
